import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import SmallScreenHeader from "../components/SmallScreenHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dylan Estate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Daylan Estate</title>
        <meta name="description" content="Generated by create next app"/>
      </head>
        <body className='min-h-screen flex flex-col overflow-x-hidden md:overflow-y-hidden'>
          <div className="w-full">
            <main>
             {children}
            </main>
          </div>
        </body>
      </html>
  );
}
